version: '3.1'


services:
  auth:
    image: quasimodo147/auth-svc:latest
    environment:
      JWT_SECRET: 'YOUR_SECRET'
      JWT_REFRESH_SECRET: 'YOUR_REFRESH_SECRET'
      RABBIT_HOST: 'some-rabbit'
      PORT: 3000
      MONGO_URI: mongodb://mongo-auth/auth
    ports:
      - 3000:3000
    links:
      - mongo-auth
      - some-rabbit
  mongo-auth:
    image: mongo:latest
    ports:
      - 27017

  expiration:
    image: quasimodo147/expiration-svc:latest
    environment:
      REDIS_HOST: some-redis
      RABBIT_URL: some-rabbit
    depends_on:
      - some-redis
      - some-rabbit
    restart: unless-stopped
  
  some-rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672
  some-redis:
    image: redis
    ports:
      - 6379
  
