version: '3.1'


services:
  auth:
    image: quasimodo147/auth-svc:latest
    environment:
      JWT_SECRET: 'YOUR_SECRET'
      PORT: 3000
      MONGO_URI: mongodb://mongo-auth/auth
    ports:
      - 3000:3000
    links:
      - mongo-auth
  mongo-auth:
    image: mongo:latest
    ports:
      - 27017
  
