version: '3.1'

services:
  auth:
    build: ./auth
    environment:
      JWT_SECRET: 'YOUR_SECRET'
      JWT_REFRESH_SECRET: 'YOUR_REFRESH_SECRET'
      RABBIT_URI: 'amqp://some-rabbit'
      PORT: 4000
      MONGO_URI: mongodb://mongo-auth/auth
    restart: unless-stopped
    ports:
      - 4000
    links:
      - mongo-auth
      - some-rabbit
  mongo-auth:
    image: mongo:latest
    ports:
      - 27017

  expiration:
    build: ./expiration
    environment:
      REDIS_HOST: some-redis
      RABBIT_URL: amqp://some-rabbit
    depends_on:
      - some-redis
      - some-rabbit
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - 3000
    links:
      - auth
    environment:
      GATEWAY_URL: http://nginx:80

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - client

  logger:
    build: ./logger
    environment:
      RABBIT_URL: amqp://some-rabbit
    depends_on:
      - some-redis
      - some-rabbit
      - auth
      - expiration
    restart: unless-stopped


  some-rabbit:
    image: rabbitmq:3-management
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
    ports:
      - 15672:15672
      - 5672
  some-redis:
    image: redis
    ports:
      - 6379
