version: '3.1'


services:
  auth:
    image: quasimodo147/auth-svc:latest
    environment:
      JWT_SECRET: 'YOUR_SECRET'
      JWT_REFRESH_SECRET: 'YOUR_REFRESH_SECRET'
      RABBIT_URI: 'amqp://some-rabbit'
      PORT: 4000
      MONGO_URI: mongodb://mongo-auth/auth
    restart: unless-stopped
    ports:
      - 4000
    links:
      - mongo-auth
      - some-rabbit
  mongo-auth:
    image: mongo:latest
    ports:
      - 27017

  expiration:
    image: quasimodo147/expiration-svc:latest
    environment:
      REDIS_HOST: some-redis
      RABBIT_URL: amqp://some-rabbit
    depends_on:
      - some-redis
      - some-rabbit
    restart: unless-stopped

  client:
    image: quasimodo147/client-nextjs:latest
    ports:
      - 3000
    links:
      - auth
    environment:
      GATEWAY_URL: http://nginx:80

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - auth
  
  some-rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672
  some-redis:
    image: redis
    ports:
      - 6379
  
