version: '3.1'

services:
  expiration:
    build: .
    environment:
      REDIS_HOST: some-redis
      RABBIT_URL: some-rabbit
    depends_on:
      - some-rabbit
      - some-redis

    restart: unless-stopped
  some-rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672
  some-redis:
    image: redis
    ports:
      - 6379