apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-depl
  template:
    metadata:
      labels:
        app: auth-depl
    spec:
      containers:
        - name: auth-depl
          image: quasimodo147/auth-svc:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: JWT_SECRET
                  key: JWT_SECRET
            - name: PORT
              value: "4000"
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_REFRESH_SECRET
            - name: MONGO_URI
              value: mongodb://mongo-auth-srv/auth
            - name: RABBIT_URI
              value: amqp://rabbit-srv
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth-depl
  ports:
    - port: 4000
      targetPort: 4000
